image: ruby:2.6

stages:
  - test
  - release

before_script:
  - apt-get update && apt-get install -y locales
  - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
  - locale-gen
  - export LC_ALL=en_US.UTF-8
  - gem install bundler:'~> 2.0' --no-document

rspec:
  stage: test
  script:
    - bin/cibuild

lint:
  stage: test
  script:
    - bin/lint

package:
  stage: release
  script:
    - bin/setup
    - bundle exec rake build
  artifacts:
    paths:
      - pkg/
    when:
      - always
