image: ruby:2.2

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - cd saml-kit
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

rspec:
  script:
    - pwd
    - ls
    - bundle exec rspec
