image: ruby:2.2

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - cd saml-kit
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

rspec:
  variables:
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
  script:
    - bundle exec rspec
